# Numpy - Tutorial 1

Numpy or numeric python is a library for multidimensional array objects and it's operation. It replace the matlab for mathematics related operations and faster than normal python list. Because python list store heterogeneous types, doesn't use contigeous memeory and finally store some additional information of the element like where it's stored and references, data types etc. But numpy only stores the same type of data in contigeous memory block.

Numpy can perform mathematical operations as well as multidimensional array operation. It's the base of various other libraries like pandas and matplotlib.

It can be installed by : pip install numpy.

## ndarray
NdArray is the main object of numpy. It describes the collection of items of the same type which can be accessed by using indices. Every item in the ndarray takes the same size of block in the memory. Each item in the ndarray is the object of data type object. To create an array:

numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

object: Sequence which will be converted to a numpy array<br>
dtype: desired data type.<br>
copy: To copy the object, by default true.<br>
order: C for row major, F for column major or A for any major(default)<br>
subok : By default, returned array forced to be a base class array. If true, sub-classes passed through<br>
ndim: minimum dimension of the resultant array.<br>

## Data types
There are several data types in numpy. Those are:<br>
1. bool: For boolean values<br>
2. int_ : default int type (int64 or int32)<br>
3. Other integers like: intc, inp, int8, int16, int32 or int64.<br>
4. Unsigned integer: uint8, uint16, uint32, uint64.<br>
5. Float: float_ for standard float and others like float16, float32, float64.<br>
6. complex data type: complex_, complex64, complex128<br>

## Attributes 
Suppose arr is an array object. Then the following attributes are:<br>
1. arr.shape: shape of the array (row, col)<br>
2. arr.ndim: dimension of array<br>
3. arr.itemsize: Length of each item in bytes.<br>

## Creation of numpy arrays

1. To create uninitialised numpy arrays: numpy.empty(shape, dtype = float, order = 'C')<br>
2. To create an array filled with zeros: numpy.zeros(shape, dtype = float, order = 'C')<br>
3. To create an array filled with ones: numpy.ones(shape, dtype = float, order = 'C')<br>
4. To create from nested lists or tuples: numpy.asarray(a, dtype = None, order = None)<br>
5. This can create an array from buffer: numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)<br>
6. To create array from iterables: numpy.fromiter(iterable, dtype, count = -1)<br>
7. To generate an array of evenly spaced values: numpy.arange(start, stop, step, dtype)<br>
8. To generate an array of evenly spaced given number of elements: numpy.linspace(start, stop, num, endpoint, retstep, dtype)<br>
9. To generate arrays of evenly spaced numbers on logscale: numpy.logspace(start, stop, num, endpoint, base, dtype)<br>
10. To create array: np.array(seq, Flags)

## Indexing and Slicing

1. Accessing by slice: 

                s = slice(start, stop, step)
                arr[s]
                
2. We can put start, stop and step directly

                arr [ start: stop: step ]
                
3. Accessing elements by indexing

                arr[idx]
                
4. First row index is given and then the column index will be put

                arr[row_idx : col_idx]
                
5. (...) symbolizes all, when put in row that means all rows in the given column and when put in the place of column, all element of the given row is accessible. However, slicing is also allowed with given index

                # this returns array of items in the second column 
                print a[...,1] 
                
                # Now we will slice all items from the second row 
                print a[1,...] 

## Advance Indexing

There are 2 types of advance indexing method available: integer, boolean.

1. Integer indexing: This indexing method can be done in following ways:

            x = np.array([[1, 2], [3, 4], [5, 6]]) 
            y = x[[0,1,2], [0,1,0]] 
            
            # output will be of rows 0,1,2 and columns 0,1,0 means it access (0,0), (1,1) and (2,0) elements from the array
            o/p => [1  4  5]
            
2. Integer indexing 2:

            x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
            
            rows = np.array([[0,0],[3,3]])
            cols = np.array([[0,2],[0,2]]) 
            y = x[rows,cols] 
            
            # the output will be
            Our array is:                                                                 
                [[ 0  1  2]                                                                   
                 [ 3  4  5]                                                                   
                 [ 6  7  8]                                                                   
                 [ 9 10 11]]

                The corner elements of this array are:                                        
                [[ 0  2]                                                                      
                 [ 9 11]] 
                 
                 

## Boolean Indexing
This type of advanced indexing is used when the resultant object is meant to be the result of Boolean operations, such as comparison operators.

            x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
            x[x>5]
            
            output:
            [[ 0  1  2] 
             [ 3  4  5] 
             [ 6  7  8] 
             [ 9 10 11]] 
             
             
             # some operarion can be done like: a[np.iscomplex(a)]

## Broadcasting
The term broadcasting refers to the ability of numpy to treat arrays of different shapes during arithmetic operations. Arithmetic opreations on arrays are done on corresponding element. If 2 arrays are of same shape, then the operation happens smoothly. 

If the size of 2 arrays are not similar and element to element operation is not possible. However, then broadcasting is applied on smaller array. The smaller array broadcasted to the ize of larger array. So that they have compatible shapes. 

Broadcasting is possible, if the following rules are satisfied:
1. Array with smaller ndim should have 1, in it's shape. Means either has 1 column or 1 row.
2. Size of each dimension of the output shape is maximum of the input size in that dimension.
3. An input can be used in calculation. If its size in a particular dimension matches the output size or have dimension value exactly 1. 
4. If an input has a dimension of size 1, the first data entry in that dimension is used for all calculation along that dimension. 

A set of arrays is said to be broadcastable, if the above rules produce a valid result and one of the following is true. 

1. Arrays have exactly same shape. 
2. Arrays have the same number of dimensions and length of each dimensions is a common length or 1. 
3. Array having too few dimensions can have it's shape prepend with a dimension of length 1, so that the above stated property is true.

Examples:

            First array:            
            [[ 0. 0. 0.]
             [ 10. 10. 10.]
             [ 20. 20. 20.]
             [ 30. 30. 30.]]

            Second array:
            [ 1. 2. 3.]

            First Array + Second Array
            [[ 1. 2. 3.]
             [ 11. 12. 13.]
             [ 21. 22. 23.]
             [ 31. 32. 33.]]
             


## Iterating Over array
Numpy package holds an iterator object known as numpy.nditer. It's an efficient multidimensional iterator object using which it's possible to iterate over an array. Each element of an array is visited using pyhon's standard iterator interface. 

        Original array is:
        [[ 0 5 10 15]
         [20 25 30 35]
         [40 45 50 55]]
         
         for x in np.nditer(a):
           print x,
           
         # output is 
         0 5 10 15 20 25 30 35 40 45 50 55
         
The order of iteration is chosen to match the memory layout of an array, without considering a particular ordering. This can be seen by iterating over the transpose of the above array.

        Original array is:
        a = [[ 0 5 10 15]
             [20 25 30 35]
             [40 45 50 55]]

        Transpose of the original array is:
        b = [[ 0 20 40]
             [ 5 25 45]
             [10 30 50]
             [15 35 55]]


        for x in np.nditer(b): 
           print x,

        Modified array is:
        0 5 10 15 20 25 30 35 40 45 50 55
        
It is possible to force nditer object to use a specific order by explicitly mentioning it. By adding another argument 'order=C' or 'order=F'.

### Modifying array values
The nditer object has another optional parameter called op_flags. Its default value is read-only, but can be set to read-write or write-only mode. This will enable modifying array elements using this iterator. (the original array will be modified)

                Original array is:
                [[ 0 5 10 15]
                 [20 25 30 35]
                 [40 45 50 55]]

                for x in np.nditer(a, op_flags = ['readwrite']):
                   x[...] = 2*x

                Modified array is:
                [[ 0 10 20 30]
                 [ 40 50 60 70]
                 [ 80 90 100 110]]
                 
### Array Manipulation
1. np.reshape(arr): To chnage the shape of the array.
2. np.flat(arr): To gives 1d flat array.
3. np.flatten(arr): Returns a copy of the array collapsed into 1 dimension.
4. np.ravel(arr): Return a ontigeous flattened array.
5. np.transpose(arr): Transpose the 2d array like matrix transpose.
6. arr.T : same as np.transpose(arr)
7. np.rollaxis(arr): Rolls the specified axis backwards
8. np.swapaxis(arr): Interchanges the two axes of an array

### Changing the dimension
1. np.broadcast(): Produces an object that mimics broadcasting
2. np.broadcast_to(arr, shape):
3. np.expand_dims(): Expands the shape of an array
4. np.squeeze(): Removes single-dimensional entries from the shape of an array

### Splitting arrays
1. split(): Splits an array into multiple sub-arrays
2. hsplit(): Splits an array into multiple sub-arrays horizontally (column-wise)
3. vsplit(): Splits an array into multiple sub-arrays vertically (row-wise)

### Adding / removing elements
1. resize(): Returns a new array with the specified shape
2. append(): Appends the values to the end of an array
3. insert(): Inserts the values along the given axis before the given indices
4. delete(): Returns a new array with sub-arrays along an axis deleted
5. unique(): Finds the unique elements of an array

### Binary operations
1. bitwise_and: Computes bitwise AND operation of array elements
2. bitwise_or: Computes bitwise OR operation of array elements
3. invert: Computes bitwise NOT
4. left_shift: Shifts bits of a binary representation to the left
5. right_shift: Shifts bits of binary representation to the right

### String operation
1. add(): Returns element-wise string concatenation for two arrays of str or Unicode
2. multiply(): Returns the string with multiple concatenation, element-wise
3. center(): Returns a copy of the given string with elements centered in a string of specified length
4. capitalize(): Returns a copy of the string with only the first character capitalized
5. title(): Returns the element-wise title cased version of the string or unicode
6. lower(): Returns an array with the elements converted to lowercase
7. upper(): Returns an array with the elements converted to uppercase
8. split(): Returns a list of the words in the string, using separatordelimiter
9. splitlines(): Returns a list of the lines in the element, breaking at the line boundaries
10. strip(): Returns a copy with the leading and trailing characters removed
11. join(): Returns a string which is the concatenation of the strings in the sequence
12. replace(): Returns a copy of the string with all occurrences of substring replaced by the new string
13. decode(): Calls str.decode element-wise
14. encode(): Calls str.encode element-wise

### Mathematical Function
1. Trigonometric function: np.sin, np.cos, np.tan, np.arcsin, np.arcos, np.arctan 
2. To convert into degree: np.degrees()
3. To round a number: np.around(arr, decimals)
4. To rounded to upper or lower: np.floor(), np.ceil().
5. Arithmetic functions like: np.add(), np.subtract(), np.multiply(), np.divide(), np.reciprocal()
6. np.power(): This function treats elements in the first input array as base and returns it raised to the power of the corresponding element in the second input array.
7. np.mod() / np.remainder(): This function returns the remainder of division of the corresponding elements in the input array. The function numpy.remainder() also produces the same result.

### complex number functions
1. np.real(): return real part of the complex number.
2. np.complex(): return complex part of the complex number.
3. np.conjugate(): return the conjugate of the complex number.
4. np.angle(): returns the angle of the complex argument.

### statistical functions
1. np.amin(), np.amax(): These functions return the minimum and the maximum from the elements in the given array along the specified axis.
2. np.ptp(): The numpy.ptp() function returns the range (maximum-minimum) of values along an axis.
3. np.percentile(): Percentile (or a centile) is a measure used in statistics indicating the value below which a given percentage of observations in a group of observations fall. The function numpy.percentile() takes the following arguments.
4. np.median(): Median is defined as the value separating the higher half of a data sample from the lower half. The numpy.median() function is used as shown in the following program.
5. np.mean(): Arithmetic mean is the sum of elements along an axis divided by the number of elements. The numpy.mean() function returns the arithmetic mean of elements in the array. If the axis is mentioned, it is calculated along it.
6. np.average(): Weighted average is an average resulting from the multiplication of each component by a factor reflecting its importance. The numpy.average() function computes the weighted average of elements in an array according to their respective weight given in another array. The function can have an axis parameter. If the axis is not specified, the array is flattened.
7. np.std(): Standard deviation is the square root of the average of squared deviations from mean. The formula for standard deviation is as follows −
8. np.var(): Variance is the average of squared deviations, i.e., mean(abs(x - x.mean())\*\*2). In other words, the standard deviation is the square root of variance.


### Sorting
1. np.sort(a, axis, kind, order): The sort() function returns a sorted copy of the input array. It has the following parameters. kind, default is quicksort.
2. np.argsort(): The numpy.argsort() function performs an indirect sort on input array, along the given axis and using a specified kind of sort to return the array of indices of data. This indices array is used to construct the sorted array.
3. np.lexsort(): function performs an indirect sort using a sequence of keys. The keys can be seen as a column in a spreadsheet. The function returns an array of indices, using which the sorted data can be obtained. Note, that the last key happens to be the primary key of sort.
4. np.argmax(), np.argmin(): These two functions return the indices of maximum and minimum elements respectively along the given axis.
5. np.nonzero(): The numpy.nonzero() function returns the indices of non-zero elements in the input array.
6. np.where(): The where() function returns the indices of elements in an input array where the given condition is satisfied.
7. np.extract(): The extract() function returns the elements satisfying any condition.

In [3]:
#### byteswapping

# The numpy.ndarray.byteswap() function toggles between the two representations: bigendian and little-endian.

## arr.byteswap()

### Copy and view
While executing the functions, some of them return a copy of the input array, while some return the view. When the contents are physically stored in another location, it is called Copy. If on the other hand, a different view of the same memory content is provided, we call it as View.

* NumPy has ndarray.view() method which is a new array object that looks at the same data of the original array. Unlike the earlier case, change in dimensions of the new array doesn’t change dimensions of the original.

* The ndarray.copy() function creates a deep copy. It is a complete copy of the array and its data, and doesn’t share with the original array.

### Matrix Library
NumPy package contains a Matrix library numpy.matlib. This module has functions that return matrices instead of ndarray objects.

1. matlib.empty(): The matlib.empty() function returns a new matrix without initializing the entries. The function takes the following parameters.
2. np.matlib.zeros(): This function returns the matrix filled with zeros.
3. np.matlib.ones(): This function returns the matrix filled with 1s.
4. np.matlib.eye(): This function returns a matrix with 1 along the diagonal elements and the zeros elsewhere. The function takes the following parameters.
5. np.matlib.identity(): The numpy.matlib.identity() function returns the Identity matrix of the given size. An identity matrix is a square matrix with all diagonal elements as 1.
6. np.matlib.rand(): The numpy.matlib.rand() function returns a matrix of the given size filled with random values.

# Linear algebra
NumPy package contains numpy.linalg module that provides all the functionality required for linear algebra. Some of the important functions in this module are described in the following table.

1. dot, vdot : Dot product of the two arrays / vectors.
2. inner : Inner product of the two arrays
3. matmul: Matrix product of the two arrays
4. determinant: Computes the determinant of the array
5. solve: Solves the linear matrix equation
6. inv : Finds the multiplicative inverse of the matrix


### Histogram
NumPy has a numpy.histogram() function that is a graphical representation of the frequency distribution of data. Rectangles of equal horizontal size corresponding to class interval called bin and variable height corresponding to frequency.

            a = np.array([22,87,5,43,56,73,55,54,11,20,51,5,79,31,27]) 
            np.histogram(a,bins = [0,20,40,60,80,100]) 
            hist,bins = np.histogram(a,bins = [0,20,40,60,80,100]) 
            print hist 
            print bins
            
            # output
            [3 4 5 2 1]
            [0 20 40 60 80 100]
            
### I/O with numpy
The ndarray objects can be saved to and loaded from the disk files. The IO functions available are :

- load() and save() functions handle /numPy binary files (with npy extension)
- loadtxt() and savetxt() functions handle normal text files

NumPy introduces a simple file format for ndarray objects. This .npy file stores data, shape, dtype and other information required to reconstruct the ndarray in a disk file such that the array is correctly retrieved even if the file is on another machine with different architecture.